apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node-gke
  template:
    metadata:
      labels:
        app: sample-node-gke
    spec:
      containers:
        - name: app
          image: us-central1-docker.pkg.dev/pelagic-chalice-346307/sample-gke-node-proj/sample-node-gke-image:a24633fa4636299264b16b310c77e931cb6c6201
          imagePullPolicy: Always
